add error log output & fix nnetfoward input

diff --git a/tonic-suite/asr/tonic-asr b/tonic-suite/asr/tonic-asr
--- a/tonic-suite/asr/tonic-asr
+++ b/tonic-suite/asr/tonic-asr
@@ -11,6 +11,7 @@ source ./path.sh
 
 root_dataset=data_set
 data_fmllr=exp/data-fmllr-tri3b # Root directory of fmllr features
+mfccdir=data/mfcc
 data_dir=$data_fmllr/local # Target directory to be decoded
 graph_dir=exp/tri3b/
 dnn_dir=exp/djinn_decode/
@@ -33,30 +34,57 @@ input=asr-list.txt
 rm ${root_dataset}/selected/${spk}/wav/*
 
 while read line;do
-  #echo $line
   cp $line ${root_dataset}/selected/${spk}/wav/
 done < $input
+
 local/voxforge_data_prep.sh ${root_dataset}/selected
 
 # Make mfcc features
-mfccdir=data/mfcc
-
 steps/make_mfcc.sh --cmd "$train_cmd" --nj 1 \
-  data/local exp/make_mfcc/local $mfccdir || exit 1;
+  data/local exp/make_mfcc/local $mfccdir;
 
+if [ $? != 0 ];
+then
+  echo "ERROR LOG FOLLOWING:"
+  cat exp/make_mfcc/local/make_mfcc_local.1.log
+  exit 1
+fi
+
+# Compute CMVN stats for the features
 steps/compute_cmvn_stats.sh data/local exp/make_mfcc/local $mfccdir || exit 1;
+
+if [ $? != 0 ];
+then
+  echo "ERROR LOG FOLLOWING:"
+  cat exp/make_mfcc/local/cmvn_local.log
+  exit 1
+fi
 
 # Make fMLLR features
 steps/nnet/make_fmllr_feats.sh --nj 1 --cmd "$train_cmd" \
         --transform-dir $graph_dir/decode \
         $data_dir data/local $graph_dir $data_dir/log $data_dir/data || exit 1;
 
+if [ $? != 0 ];
+then
+  echo "ERROR LOG FOLLOWING:"
+  cat exp/data-fmllr-tri3b/local/log/make_fmllr_feats.1.log
+  exit 1
+fi
+
 # Running decode
 steps/nnet/decode.sh --djinn $djinn --hostname $hostname --portno $portno \
                     --nj 1 --cmd "$decode_cmd" --config conf/decode_dnn.config \
-                    --nnet $dnn_dir/final.nnet --acwt 0.1 \
+                    --acwt 0.1 \
                     --common $common --network $network --weights $weights \
-                    $graph_dir/graph/ $data_dir $target_dir || exit 1;
+                    $graph_dir/graph/ $data_dir $target_dir;
+
+if [ $? != 0 ];
+then
+  echo "ERROR LOG FOLLOWING:"
+  cat exp/djinn_decode/decode_local/log/decode.1.log
+  exit 1
+fi
 
 # grabbing output from log
 logfile=${target_dir}/log/decode.1.log
